//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NikitaNikita2313.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int IdPerson { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public int IdRole { get; set; }
        public int IdGender { get; set; }
<<<<<<< HEAD

        public string FIO { get => $"{Name} {Password}"; }
=======
>>>>>>> 94d56a20f5d3d2d5a73bd5cd4f2d00df29deea19
    
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
    }
}
